
package org.example.policyregistration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolicyRegistration", targetNamespace = "http://www.example.org/PolicyRegistration/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PolicyRegistration {


    /**
     * 
     * @param memberInfo
     * @return
     *     returns org.example.policyregistration.PolicyDetails
     */
    @WebMethod(action = "http://www.example.org/PolicyRegistration/NewOperation")
    @WebResult(name = "PolicyDetails", targetNamespace = "http://www.example.org/PolicyRegistration/", partName = "policyDetails")
    public PolicyDetails enroll(
        @WebParam(name = "MemberPolicyInput", targetNamespace = "http://www.example.org/PolicyRegistration/", partName = "memberInfo")
        MemberPolicyInput memberInfo);

}
