
package org.example.policyregistration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PolicyRegistration", targetNamespace = "http://www.example.org/PolicyRegistration/", wsdlLocation = "file:/C:/Users/naabbas/Documents/personal/sts/ContractFirstJaxWS/WebContent/WEB-INF/PolicyRegistration.wsdl")
public class PolicyRegistration_Service
    extends Service
{

    private final static URL POLICYREGISTRATION_WSDL_LOCATION;
    private final static WebServiceException POLICYREGISTRATION_EXCEPTION;
    private final static QName POLICYREGISTRATION_QNAME = new QName("http://www.example.org/PolicyRegistration/", "PolicyRegistration");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/naabbas/Documents/personal/sts/ContractFirstJaxWS/WebContent/WEB-INF/PolicyRegistration.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POLICYREGISTRATION_WSDL_LOCATION = url;
        POLICYREGISTRATION_EXCEPTION = e;
    }

    public PolicyRegistration_Service() {
        super(__getWsdlLocation(), POLICYREGISTRATION_QNAME);
    }

    public PolicyRegistration_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLICYREGISTRATION_QNAME, features);
    }

    public PolicyRegistration_Service(URL wsdlLocation) {
        super(wsdlLocation, POLICYREGISTRATION_QNAME);
    }

    public PolicyRegistration_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLICYREGISTRATION_QNAME, features);
    }

    public PolicyRegistration_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyRegistration_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PolicyRegistration
     */
    @WebEndpoint(name = "PolicyRegistrationSOAP")
    public PolicyRegistration getPolicyRegistrationSOAP() {
        return super.getPort(new QName("http://www.example.org/PolicyRegistration/", "PolicyRegistrationSOAP"), PolicyRegistration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyRegistration
     */
    @WebEndpoint(name = "PolicyRegistrationSOAP")
    public PolicyRegistration getPolicyRegistrationSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/PolicyRegistration/", "PolicyRegistrationSOAP"), PolicyRegistration.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLICYREGISTRATION_EXCEPTION!= null) {
            throw POLICYREGISTRATION_EXCEPTION;
        }
        return POLICYREGISTRATION_WSDL_LOCATION;
    }

}
